/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment2java.view;

import assignment2java.model.Nguoi;
import assignment2java.model.Sach;
import assignment2java.repository.RepositoryNguoi;
import assignment2java.repository.RepositorySach;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author longg
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form HomeNguoi
     */
    RepositoryNguoi repositoryNguoi = new RepositoryNguoi();
    RepositorySach repositorySach = new RepositorySach();
    ArrayList<Sach> loaiList = repositorySach.getList();
    
    public Home() {
        initComponents();
        loadNguoi(repositoryNguoi.getList());
        loadSach(repositorySach.getList());
        loadComboBoxLoai(loaiList);
    }
    
    void loadNguoi(ArrayList<Nguoi> nList) {
        DefaultTableModel tableModel = (DefaultTableModel) tblNguoi.getModel();
        tableModel.setRowCount(0);
        
        for (Nguoi n : nList) {
            tableModel.addRow(new Object[] {
                n.getID(),
                n.getHoTen(),
                n.getGioiTinh(),
            });
        }
    }
    
    void loadSach(ArrayList<Sach> sList) {
        DefaultTableModel tableModel = (DefaultTableModel) tblSach.getModel();
        tableModel.setRowCount(0);
        
        for (Sach s : sList) {
            tableModel.addRow(new Object[] {
                s.getID(),
                s.getTenSach(),
                s.getGiaBan(),
                s.getLoai(),
            });
        }
    }
    
    void loadComboBoxLoai(ArrayList<Sach> itemLoai) {
        DefaultComboBoxModel<String> comboBoxModel = (DefaultComboBoxModel<String>) cboLoai.getModel();
        comboBoxModel.removeAllElements();

        for (Sach s : itemLoai) {
            comboBoxModel.addElement(s.getLoai());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIDNguoi = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        btnAddNguoi = new javax.swing.JButton();
        btnUpdateNguoi = new javax.swing.JButton();
        btnRemoveNguoi = new javax.swing.JButton();
        btnSearchGender = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        btnSearchPrice = new javax.swing.JButton();
        btnAddSach = new javax.swing.JButton();
        btnUpdateSach = new javax.swing.JButton();
        btnRemoveSach = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNguoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Họ tên", "Giới tính"
            }
        ));
        tblNguoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoi);

        jLabel1.setText("ID");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Giới tính");

        buttonGroup1.add(rdNam);
        rdNam.setText("Nam");

        buttonGroup1.add(rdNu);
        rdNu.setText("Nữ");

        btnAddNguoi.setText("Add");
        btnAddNguoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNguoiMouseClicked(evt);
            }
        });

        btnUpdateNguoi.setText("Update");
        btnUpdateNguoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateNguoiMouseClicked(evt);
            }
        });

        btnRemoveNguoi.setText("Remove");
        btnRemoveNguoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveNguoiMouseClicked(evt);
            }
        });

        btnSearchGender.setText("SearchGender");
        btnSearchGender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchGenderMouseClicked(evt);
            }
        });

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên sách", "Giá bán", "Loại"
            }
        ));
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSach);

        jLabel4.setText("Tên sách");

        jLabel5.setText("Giá bán");

        jLabel6.setText("ID");

        jLabel7.setText("Loại");

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSearchPrice.setText("SearchPrice");
        btnSearchPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchPriceMouseClicked(evt);
            }
        });

        btnAddSach.setText("Add");
        btnAddSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddSachMouseClicked(evt);
            }
        });

        btnUpdateSach.setText("Update");
        btnUpdateSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateSachMouseClicked(evt);
            }
        });

        btnRemoveSach.setText("Remove");
        btnRemoveSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveSachMouseClicked(evt);
            }
        });

        jLabel8.setText("Min");

        jLabel9.setText("Max");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rdNam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdNu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDSach, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddSach, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateSach, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveSach, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIDNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rdNam)
                            .addComponent(rdNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddNguoi)
                            .addComponent(btnUpdateNguoi)
                            .addComponent(btnRemoveNguoi)
                            .addComponent(btnSearchGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtIDSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddSach)
                            .addComponent(btnUpdateSach)
                            .addComponent(btnRemoveSach)
                            .addComponent(btnSearchPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblNguoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiMouseClicked
        // TODO add your handling code here:
        int row = tblNguoi.getSelectedRow();
        
        Integer ID = (Integer) tblNguoi.getValueAt(row, 0);
        Nguoi n = repositoryNguoi.details(ID);
        
        txtIDNguoi.setText(String.valueOf(n.getID()));
        txtHoTen.setText(String.valueOf(n.getHoTen()));
        if (n.getGioiTinh().equals("Nam")) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
    }//GEN-LAST:event_tblNguoiMouseClicked

    private void btnAddNguoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNguoiMouseClicked
        // TODO add your handling code here:
        Integer ID = Integer.valueOf(txtIDNguoi.getText().trim());
        String hoTen = txtHoTen.getText().trim();
        String gioiTinh;
        if (rdNam.isSelected()) {
            gioiTinh = "Nam";
        } else {
            gioiTinh = "Nu";
        }
        
        Nguoi n = new Nguoi(ID, hoTen, gioiTinh);
        Boolean kq = repositoryNguoi.add(n);
        
        if (kq == true) {
            JOptionPane.showMessageDialog(this, "Them thanh cong");
            loadNguoi(repositoryNguoi.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Them that bai");
        }
    }//GEN-LAST:event_btnAddNguoiMouseClicked

    private void btnUpdateNguoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateNguoiMouseClicked
        // TODO add your handling code here:
        Integer ID = Integer.valueOf(txtIDNguoi.getText().trim());
        String hoTen = txtHoTen.getText().trim();
        String gioiTinh;
        if (rdNam.isSelected()) {
            gioiTinh = "Nam";
        } else {
            gioiTinh = "Nu";
        }
        
        Nguoi n = new Nguoi(ID, hoTen, gioiTinh);
        Boolean kq = repositoryNguoi.update(n);
        
        if (kq == true) {
            JOptionPane.showMessageDialog(this, "Cap nhat thanh cong");
            loadNguoi(repositoryNguoi.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Cap nhat that bai");
        }
    }//GEN-LAST:event_btnUpdateNguoiMouseClicked

    private void btnRemoveNguoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveNguoiMouseClicked
        // TODO add your handling code here:
        Integer ID = Integer.valueOf(txtIDNguoi.getText().trim());

        Boolean kq = repositoryNguoi.remove(ID);
        
        if (kq == true) {
            JOptionPane.showMessageDialog(this, "Xoa thanh cong");
            loadNguoi(repositoryNguoi.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Xoa that bai");
        }
    }//GEN-LAST:event_btnRemoveNguoiMouseClicked

    private void btnSearchGenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchGenderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchGenderMouseClicked

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        // TODO add your handling code here:
        int row = tblSach.getSelectedRow();
        
        Integer ID = (Integer) tblSach.getValueAt(row, 0);
        Sach s = repositorySach.details(ID);
        
        txtIDSach.setText(String.valueOf(s.getID()));
        txtTenSach.setText(String.valueOf(s.getTenSach()));
        txtGiaBan.setText(String.valueOf(s.getGiaBan()));
        cboLoai.setSelectedItem(String.valueOf(s.getLoai()));
    }//GEN-LAST:event_tblSachMouseClicked

    private void btnAddSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddSachMouseClicked
        // TODO add your handling code here:
        Integer ID = Integer.valueOf(txtIDSach.getText().trim());
        String tenSach = txtTenSach.getText().trim();
        Double giaBan = Double.valueOf(txtGiaBan.getText().trim());
        String loai = cboLoai.getSelectedItem().toString();
        
        Sach s = new Sach(ID, tenSach, giaBan, loai);
        Boolean kq = repositorySach.add(s);
        
        if (kq == true) {
            JOptionPane.showMessageDialog(this, "Them thanh cong");
            loadSach(repositorySach.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Them that bai");
        }
    }//GEN-LAST:event_btnAddSachMouseClicked

    private void btnUpdateSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateSachMouseClicked
        // TODO add your handling code here:
        Integer ID = Integer.valueOf(txtIDSach.getText().trim());
        String tenSach = txtTenSach.getText().trim();
        Double giaBan = Double.valueOf(txtGiaBan.getText().trim());
        String loai = cboLoai.getSelectedItem().toString();
        
        Sach s = new Sach(ID, tenSach, giaBan, loai);
        Boolean kq = repositorySach.update(s);
        
        if (kq == true) {
            JOptionPane.showMessageDialog(this, "Cap nhat thanh cong");
            loadSach(repositorySach.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Cap nhat that bai");
        }
    }//GEN-LAST:event_btnUpdateSachMouseClicked

    private void btnRemoveSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveSachMouseClicked
        // TODO add your handling code here:
        Integer ID = Integer.valueOf(txtIDSach.getText().trim());
        
        Boolean kq = repositorySach.remove(ID);
        
        if (kq == true) {
            JOptionPane.showMessageDialog(this, "Xoa thanh cong");
            loadSach(repositorySach.getList());
        } else {
            JOptionPane.showMessageDialog(this, "Xoa that bai");
        }
    }//GEN-LAST:event_btnRemoveSachMouseClicked

    private void btnSearchPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchPriceMouseClicked
        // TODO add your handling code here:
        Double min = Double.valueOf(txtMin.getText().trim());
        Double max = Double.valueOf(txtMax.getText().trim());
        
        ArrayList<Sach> sList = repositorySach.searchPrice(min, max);
        loadSach(sList);
    }//GEN-LAST:event_btnSearchPriceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNguoi;
    private javax.swing.JButton btnAddSach;
    private javax.swing.JButton btnRemoveNguoi;
    private javax.swing.JButton btnRemoveSach;
    private javax.swing.JButton btnSearchGender;
    private javax.swing.JButton btnSearchPrice;
    private javax.swing.JButton btnUpdateNguoi;
    private javax.swing.JButton btnUpdateSach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblNguoi;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtIDNguoi;
    private javax.swing.JTextField txtIDSach;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
